# config_KNN.yaml
seed: 42
data:
  unobserved_proportion: 0.2
  h: 24
  N_sub: 25
  u: 1
  train_sample_size: 2000
  val_sample_size: 2000
  test_sample_size: 20000
model:
  name: "KNN"
  params:
    k: 3
    eps: 1e-8
loss:
  name: "L1Loss"
  params:
    reduction: "mean"
training:
  epochs: 500
  batch_size: 128
  lr: 0.001
  early_stopping_patience: 20
  min_delta: 0.0001
  lr_scheduler: true
  patience_lr: 20
  factor_lr: 0.5
paths:
  save_path: "./checkpoints/best_model_knn.pth"
  log_dir: "./logs/knn"
device: "cpu"
